services:
  web:
    image: nginx:alpine
    container_name: phpeggy_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - phpeggy-data:/app
    links:
      - php
    depends_on:
      - php
  php:
    container_name: phpeggy_php
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/xdebug_out:/tmp/xdebug_out
      - phpeggy-data:/app

volumes:
  phpeggy-data:
    name: phpeggy-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/marcel/phpeggy'
