"use strict";

const peggyVersion = require("peggy/package.json").version;
const phpeggyVersion = require("../../../package.json").version;

module.exports = [
  "<?php",
  "/**",
  ` * Generated by Peggy ${peggyVersion} with PHPeggy plugin ${phpeggyVersion}`,
  " *",
  " * https://peggyjs.org/",
  " * https://github.com/marcelbolten/phpeggy",
  " */",
  "",
];
