<?php
/*
 * Generated by Peggy 1.2.0 with PHPeggy plugin 2.0.0
 *
 * https://peggyjs.org/
 */

declare(strict_types=1);

namespace PHPeggy;

/* BEGIN Useful functions */
/* chr_unicode - get unicode character from its char code */
if (!function_exists("PHPeggy\\chr_unicode")) {
    /** @param float|int $code */
    function chr_unicode($code): string
    {
        return html_entity_decode("&#" . (int) $code .";", ENT_QUOTES, "UTF-8");
    }
}

/* ord_unicode - get unicode char code from string */
if (!function_exists("PHPeggy\\ord_unicode")) {
    function ord_unicode(string $character): int
    {
        if (strlen($character) === 1) {
            return ord($character);
        }
        $json = json_encode($character, JSON_THROW_ON_ERROR);
        $utf16_1 = (int) hexdec(substr($json, 3, 4));
        if (substr($json, 7, 2) === "\u") {
            $utf16_2 = (int) hexdec(substr($json, 9, 4));
            return 0x10000 + (($utf16_1 & 0x3ff) << 10) + ($utf16_2 & 0x3ff);
        } else {
            return $utf16_1;
        }
    }
}

/* peg_regex_test - multibyte regex test */
if (!function_exists("PHPeggy\\peg_regex_test")) {
    function peg_regex_test(string $pattern, string $string): bool
    {
        if (substr($pattern, -1) === "i") {
            return (bool) mb_eregi(substr($pattern, 1, -2), $string);
        } else {
            return (bool) mb_ereg(substr($pattern, 1, -1), $string);
        }
    }
}

/* BEGIN global initializer code */
// The `maybeJSON` function is not needed in PHP because its return semantics
// are the same as `json_decode`
/* END global initializer code */

/* Syntax error exception */
if (!class_exists("PHPeggy\\SyntaxError", false)) {
    class SyntaxError extends \Exception
    {
        public string $name = "SyntaxError";
        /** @var ?array<int, pegExpectation> $expected */
        public ?array $expected;
        public string $found;
        public int $grammarOffset;
        public int $grammarLine;
        public int $grammarColumn;
        public \stdClass $location;

        /**
         * @param ?array<int, pegExpectation> $expected
         */
        public function __construct(?string $message, ?array $expected, string $found, int $offset, int $line, int $column, \stdClass $location)
        {
            parent::__construct($message ?? "", 0);
            $this->expected = $expected;
            $this->found = $found;
            $this->grammarOffset = $offset;
            $this->grammarLine = $line;
            $this->grammarColumn = $column;
            $this->location = $location;
        }

        /**
         * @param array<int, array<string, string>> $sources
         */
        public function format(array $sources): string
        {
            $str = $this->name . ": " . $this->message;
            if (!empty($this->location->source)) {
                $src = null;
                for ($k = 0; $k < count($sources); $k++) {
                    if ($sources[$k]["source"] === $this->location->source) {
                        $src = preg_split("/\r\n|\n|\r/", $sources[$k]["text"]);
                        break;
                    }
                }
                $s = $this->location->start;
                $loc = $this->location->source . ":" . $s->line . ":" . $s->column;
                if ($src) {
                    $e = $this->location->end;
                    $filler = $this->peg_padEnd("", $s->line !== 0 ? (int) floor(log10($s->line) + 1) : 1);
                    $line = $src[$s->line - 1];
                    $last = $s->line === $e->line ? $e->column : strlen($line) + 1;
                    $str .= "\n --> " . $loc . "\n"
                        . $filler . " |\n"
                        . $s->line . " | " . $line . "\n"
                        . $filler . " | " . $this->peg_padEnd("", $s->column - 1)
                        . $this->peg_padEnd("", $last - $s->column, "^");
                } else {
                    $str .= "\n at " . $loc;
                }
            }
            return $str;
        }

        private function peg_padEnd(string $str, int $targetLength, string $padString = " "): string
        {
            if (strlen($str) > $targetLength) {
                return $str;
            }
            $targetLength -= strlen($str);
            $padString .= str_repeat($padString, $targetLength);
            return $str . substr($padString, 0, $targetLength);
        }
    }
}

class pegExpectation
{
    public ?string $type;
    public ?string $description;
    public ?string $value;
    public ?string $ignoreCase;

    public function __construct(string $type = null, string $description = null, string $value = null, string $ignoreCase = null)
    {
        $this->type = $type;
        $this->description = $description;
        $this->value = $value;
        $this->ignoreCase = $ignoreCase;
    }
}

class pegCacheItem
{
    public int $nextPos;
    /** @var mixed $result */
    public $result;

    /** @param mixed $result */
    public function __construct(int $nextPos, $result)
    {
        $this->nextPos = $nextPos;
        $this->result = $result;
    }
}

class pegCachedPosDetails
{
    public int $line;
    public int $column;
    public bool $seenCR;

    public function __construct(int $line = 1, int $column = 1, bool $seenCR = false)
    {
        $this->line = $line;
        $this->column = $column;
        $this->seenCR = $seenCR;
    }
}
class Parser
{
    private int $peg_currPos = 0;
    private int $peg_reportedPos = 0;
    private int $peg_cachedPos = 0;
    private pegCachedPosDetails $peg_cachedPosDetails;
    private int $peg_maxFailPos = 0;
    /** @var array<int, pegExpectation> $peg_maxFailExpected */
    private array $peg_maxFailExpected = [];
    private int $peg_silentFails = 0;
    /** @var array<int, string> $input */
    private array $input = [];
    private int $input_length = 0;
    private \stdClass $peg_FAILED;
    private string $peg_source = "";

    private string $peg_l0 = "<!--";
    private string $peg_l1 = "wp:";
    private string $peg_l2 = "/-->";
    private string $peg_l3 = "-->";
    private string $peg_l4 = "/wp:";
    private string $peg_l5 = "/";
    private string $peg_l6 = "{";
    private string $peg_l7 = "}";
    /** @var string */
    private string $peg_c0 = "/^[a-zA-Z]/";
    /** @var string */
    private string $peg_c1 = "/^[0-9]/";
    /** @var string */
    private string $peg_c2 = "/^[-_]/";
    /** @var string */
    private string $peg_c3 = "/^[ \\t\\r\\n]/";
    /** @var string */
    private string $peg_c4 = "/^[\\r\\n]/";
    /** @var string */
    private string $peg_c5 = "/^[ \\t]/";
    private pegExpectation $peg_e0;
    private pegExpectation $peg_e1;
    private pegExpectation $peg_e2;
    private pegExpectation $peg_e3;
    private pegExpectation $peg_e4;
    private pegExpectation $peg_e5;
    private pegExpectation $peg_e6;
    private pegExpectation $peg_e7;
    private pegExpectation $peg_e8;
    private pegExpectation $peg_e9;
    private pegExpectation $peg_e10;
    private pegExpectation $peg_e11;
    private pegExpectation $peg_e12;
    private pegExpectation $peg_e13;
    private pegExpectation $peg_e14;

    public function __construct()
    {
        $this->peg_FAILED = new \stdClass();
        $this->peg_cachedPosDetails = new pegCachedPosDetails();
        $this->peg_e0 = new pegExpectation("literal", "\"<!--\"", "<!--", "false");
        $this->peg_e1 = new pegExpectation("literal", "\"wp:\"", "wp:", "false");
        $this->peg_e2 = new pegExpectation("literal", "\"/-->\"", "/-->", "false");
        $this->peg_e3 = new pegExpectation("literal", "\"-->\"", "-->", "false");
        $this->peg_e4 = new pegExpectation("literal", "\"/wp:\"", "/wp:", "false");
        $this->peg_e5 = new pegExpectation("literal", "\"/\"", "/", "false");
        $this->peg_e6 = new pegExpectation("literal", "\"{\"", "{", "false");
        $this->peg_e7 = new pegExpectation("literal", "\"}\"", "}", "false");
        $this->peg_e8 = new pegExpectation("any", "any character");
        $this->peg_e9 = new pegExpectation("class", "[a-zA-Z]", "[a-zA-Z]", "false");
        $this->peg_e10 = new pegExpectation("class", "[0-9]", "[0-9]", "false");
        $this->peg_e11 = new pegExpectation("class", "[-_]", "[-_]", "false");
        $this->peg_e12 = new pegExpectation("class", "[ \\t\\r\\n]", "[ \\t\\r\\n]", "false");
        $this->peg_e13 = new pegExpectation("class", "[\\r\\n]", "[\\r\\n]", "false");
        $this->peg_e14 = new pegExpectation("class", "[ \\t]", "[ \\t]", "false");
    }

    /**
     * @param string|array<int, string> $input
     * @param array<int, mixed> $args
     * @return mixed
     */
    public function parse($input, array ...$args)
    {
        /** @var array<string, string> $options */
        $options = $args[0] ?? [];
        $this->cleanup_state();

        if (is_array($input)) {
            $this->input = $input;
        } else {
            preg_match_all("/./us", $input, $match);
            $this->input = $match[0];
        }
        $this->input_length = count($this->input);
        $this->peg_source = $options["grammarSource"] ?? "";

        $old_regex_encoding = (string) mb_regex_encoding();
        mb_regex_encoding("UTF-8");

        $peg_startRuleFunctions = ["Document" => [$this, "peg_parse_Document"]];
        $peg_startRuleFunction = [$this, "peg_parse_Document"];
        if (isset($options["startRule"])) {
            if (!(isset($peg_startRuleFunctions[$options["startRule"]]))) {
                throw new \Exception("Can't start parsing from rule \"" . $options["startRule"] . "\".");
            }

            $peg_startRuleFunction = $peg_startRuleFunctions[$options["startRule"]];
        }

        $peg_result = call_user_func($peg_startRuleFunction);

        mb_regex_encoding($old_regex_encoding);

        if ($peg_result !== $this->peg_FAILED && $this->peg_currPos === $this->input_length) {
            // Free up memory
            $this->cleanup_state();
            return $peg_result;
        }
        if ($peg_result !== $this->peg_FAILED && $this->peg_currPos < $this->input_length) {
            $this->peg_fail(new pegExpectation("end", "end of input"));
        }

        $exception = $this->peg_buildException(null, $this->peg_maxFailExpected, $this->peg_maxFailPos);
        // Free up memory
        $this->cleanup_state();
        throw $exception;
    }

    private function cleanup_state(): void
    {
        $this->peg_currPos = 0;
        $this->peg_reportedPos = 0;
        $this->peg_cachedPos = 0;
        $this->peg_cachedPosDetails = new pegCachedPosDetails();
        $this->peg_maxFailPos = 0;
        $this->peg_maxFailExpected = [];
        $this->peg_silentFails = 0;
        $this->input = [];
        $this->input_length = 0;
        $this->peg_source = "";
    }

    private function input_substr(int $start, int $length): string
    {
        if ($length === 1 && $start < $this->input_length) {
            return $this->input[$start];
        }
        $substr = "";
        $max = min($start + $length, $this->input_length);
        for ($i = $start; $i < $max; $i++) {
            $substr .= $this->input[$i];
        }
        return $substr;
    }

    private function text(): string
    {
        return $this->input_substr($this->peg_reportedPos, $this->peg_currPos - $this->peg_reportedPos);
    }

    private function offset(): int
    {
        return $this->peg_reportedPos;
    }

    /** @return array<string, string|int> */
    private function range(): array
    {
        return ["source" => $this->peg_source, "start" => $this->peg_reportedPos, "end" => $this->peg_currPos];
    }

    private function location(bool $fail = false): \stdClass
    {
        $start = $this->peg_reportedPos;
        $end = $this->peg_currPos;
        if ($fail) {
            $start = $this->peg_maxFailPos;
            $end = $this->peg_maxFailPos + ($this->peg_maxFailPos < count($this->input) ? 1 : 0);
        }
        $compute_pd_start = $this->peg_computePosDetails($start);
        $compute_pd_end = $this->peg_computePosDetails($end);

        return (object) [
            "source" => $this->peg_source,
            "start" => (object) [
                "offset" => $start,
                "line" => $compute_pd_start->line,
                "column" => $compute_pd_start->column,
            ],
            "end" => (object) [
                "offset" => $end,
                "line" => $compute_pd_end->line,
                "column" => $compute_pd_end->column,
            ],
        ];
    }

    private function line(): int
    {
        $compute_pd = $this->peg_computePosDetails($this->peg_reportedPos);
        return $compute_pd->line;
    }

    private function column(): int
    {
        $compute_pd = $this->peg_computePosDetails($this->peg_reportedPos);
        return $compute_pd->column;
    }

    private function expected(string $description): void
    {
        throw $this->peg_buildException(
            null,
            [new pegExpectation("other", $description)],
            $this->peg_reportedPos
        );
    }

    private function error(string $message): void
    {
        throw $this->peg_buildException($message, null, $this->peg_reportedPos);
    }

    private function peg_advancePos(pegCachedPosDetails &$details, int $startPos, int $endPos): void
    {
        for ($p = $startPos; $p < $endPos; $p++) {
            $ch = $this->input_substr($p, 1);
            if ($ch === "\n") {
                if (!$details->seenCR) {
                    $details->line++;
                }
                $details->column = 1;
                $details->seenCR = false;
            } elseif ($ch === "\r" || $ch === "\u2028" || $ch === "\u2029") {
                $details->line++;
                $details->column = 1;
                $details->seenCR = true;
            } else {
                $details->column++;
                $details->seenCR = false;
            }
        }
    }

    private function peg_computePosDetails(int $pos): pegCachedPosDetails
    {
        if ($this->peg_cachedPos !== $pos) {
            if ($this->peg_cachedPos > $pos) {
                $this->peg_cachedPos = 0;
                $this->peg_cachedPosDetails = new pegCachedPosDetails();
            }
            $this->peg_advancePos($this->peg_cachedPosDetails, $this->peg_cachedPos, $pos);
            $this->peg_cachedPos = $pos;
        }

        return $this->peg_cachedPosDetails;
    }

    private function peg_fail(pegExpectation $expected): void
    {
        if ($this->peg_currPos < $this->peg_maxFailPos) {
            return;
        }

        if ($this->peg_currPos > $this->peg_maxFailPos) {
            $this->peg_maxFailPos = $this->peg_currPos;
            $this->peg_maxFailExpected = [];
        }

        $this->peg_maxFailExpected[] = $expected;
    }

    private function peg_buildException_expectedComparator(pegExpectation $a, pegExpectation $b): int
    {
        $a = (array) $a;
        $b = (array) $b;
        if ($a["description"] < $b["description"]) {
            return -1;
        } elseif ($a["description"] > $b["description"]) {
            return 1;
        } else {
            return 0;
        }
    }

    /** @param array<int, pegExpectation> $expected */
    private function peg_buildException(?string $message, ?array $expected, int $pos): SyntaxError
    {
        $posDetails = $this->peg_computePosDetails($pos);
        $found = $pos < $this->input_length ? $this->input[$pos] : null;

        if ($expected !== null) {
            usort($expected, [$this, "peg_buildException_expectedComparator"]);
            $i = 1;
            while ($i < count($expected)) {
                if ($expected[$i - 1] === $expected[$i]) {
                    array_splice($expected, $i, 1);
                } else {
                    $i++;
                }
            }
        }

        if ($message === null && $expected !== null) {
            $expectedDescs = array_fill(0, count($expected), null);

            for ($i = 0; $i < count($expected); $i++) {
                $expectedDescs[$i] = $expected[$i]->description;
            }

            $expectedDesc = count($expected) > 1
                ? join(", ", array_slice($expectedDescs, 0, -1))
                    . " or "
                    . $expectedDescs[count($expected) - 1]
                : $expectedDescs[0];

            $foundDesc = $found ? json_encode($found) : "end of input";

            $message = "Expected " . $expectedDesc . " but " . $foundDesc . " found.";
        }

        return new SyntaxError(
            $message,
            $expected,
            $found ?? "",
            $pos,
            $posDetails->line,
            $posDetails->column,
            $this->location(true)
        );
    }

    /**
     * @param mixed $blockName
     * @param mixed $attrs
     * @return mixed
     */
    private function peg_f0($blockName, $attrs)
    {
        return [
            'blockName' => $blockName,
            'attrs' => $attrs,
            'rawContent' => '',
        ];
    }

    /**
     * @param mixed $s
     * @param mixed $ts
     * @param mixed $e
     * @return mixed
     */
    private function peg_f1($s, $ts, $e)
    {
        return $s['blockName'] === $e['blockName'];
    }

    /**
     * @param mixed $s
     * @param mixed $ts
     * @param mixed $e
     * @return mixed
     */
    private function peg_f2($s, $ts, $e)
    {
        return [
            'blockName' => $s['blockName'],
            'attrs' => $s['attrs'],
            'rawContent' => implode('', $ts),
        ];
    }

    /**
     * @param mixed $blockName
     * @param mixed $attrs
     * @return mixed
     */
    private function peg_f3($blockName, $attrs)
    {
        return [
            'blockName' => $blockName,
            'attrs' => $attrs,
        ];
    }

    /**
     * @param mixed $blockName
     * @return mixed
     */
    private function peg_f4($blockName)
    {
        return [
            'blockName' => $blockName,
        ];
    }

    /**
     * @param mixed $attrs
     * @return mixed
     */
    private function peg_f5($attrs)
    {
        return json_decode($attrs, true);
    }

    /** @return mixed */
    private function peg_parse_Document()
    {
        $s0 = $this->peg_parse_WP_Block_List();

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WP_Block_List()
    {
        $s0 = [];
        $s1 = $this->peg_parse_WP_Block();
        while ($s1 !== $this->peg_FAILED) {
            $s0[] = $s1;
            $s1 = $this->peg_parse_WP_Block();
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WP_Block()
    {
        $s0 = $this->peg_parse_WP_Block_Void();
        if ($s0 === $this->peg_FAILED) {
            $s0 = $this->peg_parse_WP_Block_Balanced();
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WP_Block_Void()
    {
        $s0 = $this->peg_currPos;
        if ($this->input_substr($this->peg_currPos, 4) === $this->peg_l0) {
            $s1 = $this->peg_l0;
            $this->peg_currPos += 4;
        } else {
            $s1 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e0);
            }
        }
        if ($s1 !== $this->peg_FAILED) {
            $s2 = [];
            $s3 = $this->peg_parse_WS();
            if ($s3 !== $this->peg_FAILED) {
                while ($s3 !== $this->peg_FAILED) {
                    $s2[] = $s3;
                    $s3 = $this->peg_parse_WS();
                }
            } else {
                $s2 = $this->peg_FAILED;
            }
            if ($s2 !== $this->peg_FAILED) {
                if ($this->input_substr($this->peg_currPos, 3) === $this->peg_l1) {
                    $s3 = $this->peg_l1;
                    $this->peg_currPos += 3;
                } else {
                    $s3 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e1);
                    }
                }
                if ($s3 !== $this->peg_FAILED) {
                    $s4 = $this->peg_parse_WP_Block_Name();
                    if ($s4 !== $this->peg_FAILED) {
                        $s5 = [];
                        $s6 = $this->peg_parse_WS();
                        if ($s6 !== $this->peg_FAILED) {
                            while ($s6 !== $this->peg_FAILED) {
                                $s5[] = $s6;
                                $s6 = $this->peg_parse_WS();
                            }
                        } else {
                            $s5 = $this->peg_FAILED;
                        }
                        if ($s5 !== $this->peg_FAILED) {
                            $s6 = $this->peg_currPos;
                            $s7 = $this->peg_parse_WP_Block_Attributes();
                            if ($s7 !== $this->peg_FAILED) {
                                $s8 = [];
                                $s9 = $this->peg_parse_WS();
                                if ($s9 !== $this->peg_FAILED) {
                                    while ($s9 !== $this->peg_FAILED) {
                                        $s8[] = $s9;
                                        $s9 = $this->peg_parse_WS();
                                    }
                                } else {
                                    $s8 = $this->peg_FAILED;
                                }
                                if ($s8 !== $this->peg_FAILED) {
                                    $s6 = $s7;
                                } else {
                                    $this->peg_currPos = $s6;
                                    $s6 = $this->peg_FAILED;
                                }
                            } else {
                                $this->peg_currPos = $s6;
                                $s6 = $this->peg_FAILED;
                            }
                            if ($s6 === $this->peg_FAILED) {
                                $s6 = null;
                            }
                            if ($this->input_substr($this->peg_currPos, 4) === $this->peg_l2) {
                                $s7 = $this->peg_l2;
                                $this->peg_currPos += 4;
                            } else {
                                $s7 = $this->peg_FAILED;
                                if ($this->peg_silentFails === 0) {
                                    $this->peg_fail($this->peg_e2);
                                }
                            }
                            if ($s7 !== $this->peg_FAILED) {
                                $this->peg_reportedPos = $s0;
                                $s0 = $this->peg_f0($s4, $s6);
                            } else {
                                $this->peg_currPos = $s0;
                                $s0 = $this->peg_FAILED;
                            }
                        } else {
                            $this->peg_currPos = $s0;
                            $s0 = $this->peg_FAILED;
                        }
                    } else {
                        $this->peg_currPos = $s0;
                        $s0 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s0;
                    $s0 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WP_Block_Balanced()
    {
        $s0 = $this->peg_currPos;
        $s1 = $this->peg_parse_WP_Block_Start();
        if ($s1 !== $this->peg_FAILED) {
            $s2 = [];
            $s3 = $this->peg_currPos;
            $s4 = $this->peg_currPos;
            $this->peg_silentFails++;
            $s5 = $this->peg_parse_WP_Block_End();
            $this->peg_silentFails--;
            if ($s5 === $this->peg_FAILED) {
                $s4 = null;
            } else {
                $this->peg_currPos = $s4;
                $s4 = $this->peg_FAILED;
            }
            if ($s4 !== $this->peg_FAILED) {
                $s5 = $this->peg_parse_Any();
                if ($s5 !== $this->peg_FAILED) {
                    $s3 = $s5;
                } else {
                    $this->peg_currPos = $s3;
                    $s3 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s3;
                $s3 = $this->peg_FAILED;
            }
            while ($s3 !== $this->peg_FAILED) {
                $s2[] = $s3;
                $s3 = $this->peg_currPos;
                $s4 = $this->peg_currPos;
                $this->peg_silentFails++;
                $s5 = $this->peg_parse_WP_Block_End();
                $this->peg_silentFails--;
                if ($s5 === $this->peg_FAILED) {
                    $s4 = null;
                } else {
                    $this->peg_currPos = $s4;
                    $s4 = $this->peg_FAILED;
                }
                if ($s4 !== $this->peg_FAILED) {
                    $s5 = $this->peg_parse_Any();
                    if ($s5 !== $this->peg_FAILED) {
                        $s3 = $s5;
                    } else {
                        $this->peg_currPos = $s3;
                        $s3 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s3;
                    $s3 = $this->peg_FAILED;
                }
            }
            $s3 = $this->peg_parse_WP_Block_End();
            if ($s3 !== $this->peg_FAILED) {
                $this->peg_reportedPos = $this->peg_currPos;
                $s4 = $this->peg_f1($s1, $s2, $s3);
                if ($s4) {
                    $s4 = null;
                } else {
                    $s4 = $this->peg_FAILED;
                }
                if ($s4 !== $this->peg_FAILED) {
                    $this->peg_reportedPos = $s0;
                    $s0 = $this->peg_f2($s1, $s2, $s3);
                } else {
                    $this->peg_currPos = $s0;
                    $s0 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WP_Block_Start()
    {
        $s0 = $this->peg_currPos;
        if ($this->input_substr($this->peg_currPos, 4) === $this->peg_l0) {
            $s1 = $this->peg_l0;
            $this->peg_currPos += 4;
        } else {
            $s1 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e0);
            }
        }
        if ($s1 !== $this->peg_FAILED) {
            $s2 = [];
            $s3 = $this->peg_parse_WS();
            if ($s3 !== $this->peg_FAILED) {
                while ($s3 !== $this->peg_FAILED) {
                    $s2[] = $s3;
                    $s3 = $this->peg_parse_WS();
                }
            } else {
                $s2 = $this->peg_FAILED;
            }
            if ($s2 !== $this->peg_FAILED) {
                if ($this->input_substr($this->peg_currPos, 3) === $this->peg_l1) {
                    $s3 = $this->peg_l1;
                    $this->peg_currPos += 3;
                } else {
                    $s3 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e1);
                    }
                }
                if ($s3 !== $this->peg_FAILED) {
                    $s4 = $this->peg_parse_WP_Block_Name();
                    if ($s4 !== $this->peg_FAILED) {
                        $s5 = [];
                        $s6 = $this->peg_parse_WS();
                        if ($s6 !== $this->peg_FAILED) {
                            while ($s6 !== $this->peg_FAILED) {
                                $s5[] = $s6;
                                $s6 = $this->peg_parse_WS();
                            }
                        } else {
                            $s5 = $this->peg_FAILED;
                        }
                        if ($s5 !== $this->peg_FAILED) {
                            $s6 = $this->peg_currPos;
                            $s7 = $this->peg_parse_WP_Block_Attributes();
                            if ($s7 !== $this->peg_FAILED) {
                                $s8 = [];
                                $s9 = $this->peg_parse_WS();
                                if ($s9 !== $this->peg_FAILED) {
                                    while ($s9 !== $this->peg_FAILED) {
                                        $s8[] = $s9;
                                        $s9 = $this->peg_parse_WS();
                                    }
                                } else {
                                    $s8 = $this->peg_FAILED;
                                }
                                if ($s8 !== $this->peg_FAILED) {
                                    $s6 = $s7;
                                } else {
                                    $this->peg_currPos = $s6;
                                    $s6 = $this->peg_FAILED;
                                }
                            } else {
                                $this->peg_currPos = $s6;
                                $s6 = $this->peg_FAILED;
                            }
                            if ($s6 === $this->peg_FAILED) {
                                $s6 = null;
                            }
                            if ($this->input_substr($this->peg_currPos, 3) === $this->peg_l3) {
                                $s7 = $this->peg_l3;
                                $this->peg_currPos += 3;
                            } else {
                                $s7 = $this->peg_FAILED;
                                if ($this->peg_silentFails === 0) {
                                    $this->peg_fail($this->peg_e3);
                                }
                            }
                            if ($s7 !== $this->peg_FAILED) {
                                $this->peg_reportedPos = $s0;
                                $s0 = $this->peg_f3($s4, $s6);
                            } else {
                                $this->peg_currPos = $s0;
                                $s0 = $this->peg_FAILED;
                            }
                        } else {
                            $this->peg_currPos = $s0;
                            $s0 = $this->peg_FAILED;
                        }
                    } else {
                        $this->peg_currPos = $s0;
                        $s0 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s0;
                    $s0 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WP_Block_End()
    {
        $s0 = $this->peg_currPos;
        if ($this->input_substr($this->peg_currPos, 4) === $this->peg_l0) {
            $s1 = $this->peg_l0;
            $this->peg_currPos += 4;
        } else {
            $s1 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e0);
            }
        }
        if ($s1 !== $this->peg_FAILED) {
            $s2 = [];
            $s3 = $this->peg_parse_WS();
            if ($s3 !== $this->peg_FAILED) {
                while ($s3 !== $this->peg_FAILED) {
                    $s2[] = $s3;
                    $s3 = $this->peg_parse_WS();
                }
            } else {
                $s2 = $this->peg_FAILED;
            }
            if ($s2 !== $this->peg_FAILED) {
                if ($this->input_substr($this->peg_currPos, 4) === $this->peg_l4) {
                    $s3 = $this->peg_l4;
                    $this->peg_currPos += 4;
                } else {
                    $s3 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e4);
                    }
                }
                if ($s3 !== $this->peg_FAILED) {
                    $s4 = $this->peg_parse_WP_Block_Name();
                    if ($s4 !== $this->peg_FAILED) {
                        $s5 = [];
                        $s6 = $this->peg_parse_WS();
                        if ($s6 !== $this->peg_FAILED) {
                            while ($s6 !== $this->peg_FAILED) {
                                $s5[] = $s6;
                                $s6 = $this->peg_parse_WS();
                            }
                        } else {
                            $s5 = $this->peg_FAILED;
                        }
                        if ($s5 !== $this->peg_FAILED) {
                            if ($this->input_substr($this->peg_currPos, 3) === $this->peg_l3) {
                                $s6 = $this->peg_l3;
                                $this->peg_currPos += 3;
                            } else {
                                $s6 = $this->peg_FAILED;
                                if ($this->peg_silentFails === 0) {
                                    $this->peg_fail($this->peg_e3);
                                }
                            }
                            if ($s6 !== $this->peg_FAILED) {
                                $this->peg_reportedPos = $s0;
                                $s0 = $this->peg_f4($s4);
                            } else {
                                $this->peg_currPos = $s0;
                                $s0 = $this->peg_FAILED;
                            }
                        } else {
                            $this->peg_currPos = $s0;
                            $s0 = $this->peg_FAILED;
                        }
                    } else {
                        $this->peg_currPos = $s0;
                        $s0 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s0;
                    $s0 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WP_Block_Name()
    {
        $s0 = $this->peg_currPos;
        $s1 = $this->peg_currPos;
        $s2 = $this->peg_parse_ASCII_Letter();
        if ($s2 !== $this->peg_FAILED) {
            $s3 = [];
            $s4 = $this->peg_parse_ASCII_AlphaNumeric();
            if ($s4 === $this->peg_FAILED) {
                $s4 = $this->peg_currPos;
                if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l5) {
                    $s5 = $this->peg_l5;
                    $this->peg_currPos++;
                } else {
                    $s5 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e5);
                    }
                }
                if ($s5 !== $this->peg_FAILED) {
                    $s6 = $this->peg_parse_ASCII_AlphaNumeric();
                    if ($s6 !== $this->peg_FAILED) {
                        $s5 = [$s5, $s6];
                        $s4 = $s5;
                    } else {
                        $this->peg_currPos = $s4;
                        $s4 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s4;
                    $s4 = $this->peg_FAILED;
                }
            }
            while ($s4 !== $this->peg_FAILED) {
                $s3[] = $s4;
                $s4 = $this->peg_parse_ASCII_AlphaNumeric();
                if ($s4 === $this->peg_FAILED) {
                    $s4 = $this->peg_currPos;
                    if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l5) {
                        $s5 = $this->peg_l5;
                        $this->peg_currPos++;
                    } else {
                        $s5 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) {
                            $this->peg_fail($this->peg_e5);
                        }
                    }
                    if ($s5 !== $this->peg_FAILED) {
                        $s6 = $this->peg_parse_ASCII_AlphaNumeric();
                        if ($s6 !== $this->peg_FAILED) {
                            $s5 = [$s5, $s6];
                            $s4 = $s5;
                        } else {
                            $this->peg_currPos = $s4;
                            $s4 = $this->peg_FAILED;
                        }
                    } else {
                        $this->peg_currPos = $s4;
                        $s4 = $this->peg_FAILED;
                    }
                }
            }
            $s2 = [$s2, $s3];
            $s1 = $s2;
        } else {
            $this->peg_currPos = $s1;
            $s1 = $this->peg_FAILED;
        }
        if ($s1 !== $this->peg_FAILED) {
            $s0 = $this->input_substr($s0, $this->peg_currPos - $s0);
        } else {
            $s0 = $s1;
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WP_Block_Attributes()
    {
        $s0 = $this->peg_currPos;
        $s1 = $this->peg_currPos;
        $s2 = $this->peg_currPos;
        if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l6) {
            $s3 = $this->peg_l6;
            $this->peg_currPos++;
        } else {
            $s3 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e6);
            }
        }
        if ($s3 !== $this->peg_FAILED) {
            $s4 = [];
            $s5 = $this->peg_currPos;
            $s6 = $this->peg_currPos;
            $this->peg_silentFails++;
            $s7 = $this->peg_currPos;
            if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l7) {
                $s8 = $this->peg_l7;
                $this->peg_currPos++;
            } else {
                $s8 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) {
                    $this->peg_fail($this->peg_e7);
                }
            }
            if ($s8 !== $this->peg_FAILED) {
                $s9 = [];
                $s10 = $this->peg_parse_WS();
                if ($s10 !== $this->peg_FAILED) {
                    while ($s10 !== $this->peg_FAILED) {
                        $s9[] = $s10;
                        $s10 = $this->peg_parse_WS();
                    }
                } else {
                    $s9 = $this->peg_FAILED;
                }
                if ($s9 !== $this->peg_FAILED) {
                    $s10 = "";
                    if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l5) {
                        $s11 = $this->peg_l5;
                        $this->peg_currPos++;
                    } else {
                        $s11 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) {
                            $this->peg_fail($this->peg_e5);
                        }
                    }
                    if ($s11 === $this->peg_FAILED) {
                        $s11 = null;
                    }
                    if ($this->input_substr($this->peg_currPos, 3) === $this->peg_l3) {
                        $s12 = $this->peg_l3;
                        $this->peg_currPos += 3;
                    } else {
                        $s12 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) {
                            $this->peg_fail($this->peg_e3);
                        }
                    }
                    if ($s12 !== $this->peg_FAILED) {
                        $s8 = [$s8, $s9, $s10, $s11, $s12];
                        $s7 = $s8;
                    } else {
                        $this->peg_currPos = $s7;
                        $s7 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s7;
                    $s7 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s7;
                $s7 = $this->peg_FAILED;
            }
            $this->peg_silentFails--;
            if ($s7 === $this->peg_FAILED) {
                $s6 = null;
            } else {
                $this->peg_currPos = $s6;
                $s6 = $this->peg_FAILED;
            }
            if ($s6 !== $this->peg_FAILED) {
                if ($this->input_length > $this->peg_currPos) {
                    $s7 = $this->input_substr($this->peg_currPos, 1);
                    $this->peg_currPos++;
                } else {
                    $s7 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e8);
                    }
                }
                if ($s7 !== $this->peg_FAILED) {
                    $s6 = [$s6, $s7];
                    $s5 = $s6;
                } else {
                    $this->peg_currPos = $s5;
                    $s5 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s5;
                $s5 = $this->peg_FAILED;
            }
            while ($s5 !== $this->peg_FAILED) {
                $s4[] = $s5;
                $s5 = $this->peg_currPos;
                $s6 = $this->peg_currPos;
                $this->peg_silentFails++;
                $s7 = $this->peg_currPos;
                if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l7) {
                    $s8 = $this->peg_l7;
                    $this->peg_currPos++;
                } else {
                    $s8 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e7);
                    }
                }
                if ($s8 !== $this->peg_FAILED) {
                    $s9 = [];
                    $s10 = $this->peg_parse_WS();
                    if ($s10 !== $this->peg_FAILED) {
                        while ($s10 !== $this->peg_FAILED) {
                            $s9[] = $s10;
                            $s10 = $this->peg_parse_WS();
                        }
                    } else {
                        $s9 = $this->peg_FAILED;
                    }
                    if ($s9 !== $this->peg_FAILED) {
                        $s10 = "";
                        if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l5) {
                            $s11 = $this->peg_l5;
                            $this->peg_currPos++;
                        } else {
                            $s11 = $this->peg_FAILED;
                            if ($this->peg_silentFails === 0) {
                                $this->peg_fail($this->peg_e5);
                            }
                        }
                        if ($s11 === $this->peg_FAILED) {
                            $s11 = null;
                        }
                        if ($this->input_substr($this->peg_currPos, 3) === $this->peg_l3) {
                            $s12 = $this->peg_l3;
                            $this->peg_currPos += 3;
                        } else {
                            $s12 = $this->peg_FAILED;
                            if ($this->peg_silentFails === 0) {
                                $this->peg_fail($this->peg_e3);
                            }
                        }
                        if ($s12 !== $this->peg_FAILED) {
                            $s8 = [$s8, $s9, $s10, $s11, $s12];
                            $s7 = $s8;
                        } else {
                            $this->peg_currPos = $s7;
                            $s7 = $this->peg_FAILED;
                        }
                    } else {
                        $this->peg_currPos = $s7;
                        $s7 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s7;
                    $s7 = $this->peg_FAILED;
                }
                $this->peg_silentFails--;
                if ($s7 === $this->peg_FAILED) {
                    $s6 = null;
                } else {
                    $this->peg_currPos = $s6;
                    $s6 = $this->peg_FAILED;
                }
                if ($s6 !== $this->peg_FAILED) {
                    if ($this->input_length > $this->peg_currPos) {
                        $s7 = $this->input_substr($this->peg_currPos, 1);
                        $this->peg_currPos++;
                    } else {
                        $s7 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) {
                            $this->peg_fail($this->peg_e8);
                        }
                    }
                    if ($s7 !== $this->peg_FAILED) {
                        $s6 = [$s6, $s7];
                        $s5 = $s6;
                    } else {
                        $this->peg_currPos = $s5;
                        $s5 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s5;
                    $s5 = $this->peg_FAILED;
                }
            }
            if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l7) {
                $s5 = $this->peg_l7;
                $this->peg_currPos++;
            } else {
                $s5 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) {
                    $this->peg_fail($this->peg_e7);
                }
            }
            if ($s5 !== $this->peg_FAILED) {
                $s3 = [$s3, $s4, $s5];
                $s2 = $s3;
            } else {
                $this->peg_currPos = $s2;
                $s2 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s2;
            $s2 = $this->peg_FAILED;
        }
        if ($s2 !== $this->peg_FAILED) {
            $s1 = $this->input_substr($s1, $this->peg_currPos - $s1);
        } else {
            $s1 = $s2;
        }
        if ($s1 !== $this->peg_FAILED) {
            $this->peg_reportedPos = $s0;
            $s1 = $this->peg_f5($s1);
        }
        $s0 = $s1;

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_ASCII_AlphaNumeric()
    {
        $s0 = $this->peg_parse_ASCII_Letter();
        if ($s0 === $this->peg_FAILED) {
            $s0 = $this->peg_parse_ASCII_Digit();
            if ($s0 === $this->peg_FAILED) {
                $s0 = $this->peg_parse_Special_Chars();
            }
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_ASCII_Letter()
    {
        if (peg_regex_test($this->peg_c0, $this->input_substr($this->peg_currPos, 1))) {
            $s0 = $this->input_substr($this->peg_currPos, 1);
            $this->peg_currPos++;
        } else {
            $s0 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e9);
            }
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_ASCII_Digit()
    {
        if (peg_regex_test($this->peg_c1, $this->input_substr($this->peg_currPos, 1))) {
            $s0 = $this->input_substr($this->peg_currPos, 1);
            $this->peg_currPos++;
        } else {
            $s0 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e10);
            }
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_Special_Chars()
    {
        if (peg_regex_test($this->peg_c2, $this->input_substr($this->peg_currPos, 1))) {
            $s0 = $this->input_substr($this->peg_currPos, 1);
            $this->peg_currPos++;
        } else {
            $s0 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e11);
            }
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_WS()
    {
        if (peg_regex_test($this->peg_c3, $this->input_substr($this->peg_currPos, 1))) {
            $s0 = $this->input_substr($this->peg_currPos, 1);
            $this->peg_currPos++;
        } else {
            $s0 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e12);
            }
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_Newline()
    {
        if (peg_regex_test($this->peg_c4, $this->input_substr($this->peg_currPos, 1))) {
            $s0 = $this->input_substr($this->peg_currPos, 1);
            $this->peg_currPos++;
        } else {
            $s0 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e13);
            }
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse__()
    {
        if (peg_regex_test($this->peg_c5, $this->input_substr($this->peg_currPos, 1))) {
            $s0 = $this->input_substr($this->peg_currPos, 1);
            $this->peg_currPos++;
        } else {
            $s0 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e14);
            }
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse___()
    {
        $s0 = [];
        $s1 = $this->peg_parse__();
        if ($s1 !== $this->peg_FAILED) {
            while ($s1 !== $this->peg_FAILED) {
                $s0[] = $s1;
                $s1 = $this->peg_parse__();
            }
        } else {
            $s0 = $this->peg_FAILED;
        }

        return $s0;
    }

    /** @return mixed */
    private function peg_parse_Any()
    {
        if ($this->input_length > $this->peg_currPos) {
            $s0 = $this->input_substr($this->peg_currPos, 1);
            $this->peg_currPos++;
        } else {
            $s0 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e8);
            }
        }

        return $s0;
    }
};
